### ISSUE TITLE
[1.16.5] "Exception in thread "main" java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'mesh'!"

### ISSUE THREAD

**Issue by aking4125** [milkev/More-Baked-Foods#2]
Hey,

There seems to be a mod conflict or other issue going on. The game "Crashes" but doesn't create a crash log. Submitting the Log instead. Strange thing is, the latest.log file stops at a certain point. But the log that the Vanilla launcher has gives more detailed information. The [Pastebin link](https://pastebin.com/B79dvjMU) contains the rest of the "Error" where the log file stops. 

[latest.log](https://github.com/milkev/More-Baked-Foods/files/6258849/latest.log)

Removing this mod has the pack loading normally. Any ideas?

**Comment by milkev** [comment]
believe i found the problem, mesh was trying to register a template file that my mod did not register.... deleting it should fix this issue
ill test it later, and it will be released alongside the next update : )

**Comment by aking4125** [comment]
Copy that.

**Comment by UpcraftLP** [comment]
> believe i found the problem, mesh was trying to register a template file that my mod did not register.... deleting it should fix this issue
> ill test it later, and it will be released alongside the next update : )

no, Mesh has nothing to do with this error. Some other mod didn't rename the example mod `modid.mixins.json` file, and therefore mixin is trying to load yours.
